
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeAliasesPackage: com.zzq.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
      logic-not-delete-value: 1
      logic-delete-value: 0
server:
  port: 9098
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myself?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

swagger:
  enable: true

knife4j:
  basic:
    enable: true
    username: admin
    password: admin

#指定日志配置文件
logging:
  config: classpath:log/logback-spring.xml